CREATE TABLE Utilizador (utilizador_id BIGSERIAL NOT NULL, nome varchar(255) NOT NULL, email varchar(255) NOT NULL UNIQUE, sexo varchar(1) NOT NULL, data_nascimento date NOT NULL, role_id BIGSERIAL NOT NULL, PRIMARY KEY (utilizador_id));
CREATE TABLE Role (role_id BIGSERIAL NOT NULL, nome_role varchar(255) NOT NULL UNIQUE, PRIMARY KEY (role_id));
CREATE TABLE Tipo_Consumivel (tipo_id BIGSERIAL NOT NULL, nome_tipo varchar(255) NOT NULL UNIQUE, PRIMARY KEY (tipo_id));
CREATE TABLE Consumivel (consumivel_id BIGSERIAL NOT NULL, nome_consumivel varchar(255) NOT NULL, tipo_id BIGSERIAL NOT NULL, codigo varchar(255) NOT NULL UNIQUE, quantidade_total int8 DEFAULT 0 NOT NULL CHECK(quantidade_total >= 0), quantidade_alocada int8 DEFAULT 0 NOT NULL CHECK(quantidade_alocada >= 0), quantidade_minima int8 DEFAULT 0 NOT NULL CHECK(quantidade_minima >= 0), quantidade_pedido int8 DEFAULT 0 NOT NULL CHECK(quantidade_pedido >= 0), PRIMARY KEY (consumivel_id));
CREATE TABLE Setor_Hospital (setor_id BIGSERIAL NOT NULL, nome_setor varchar(255) NOT NULL, localizacao varchar(255) NOT NULL, responsavel_id BIGSERIAL NULL, PRIMARY KEY (setor_id));
CREATE TABLE Requerimento (requerimento_id BIGSERIAL NOT NULL, setor_id BIGSERIAL NOT NULL, user_id_pedido BIGSERIAL NOT NULL, urgente BOOLEAN NOT NULL, tipo_requerimento varchar(20) DEFAULT 'Interno' CHECK(tipo_requerimento IN ('Interno', 'Externo')), PRIMARY KEY (requerimento_id));
CREATE TABLE Requerimento_Externo (requerimento_externo_id SERIAL NOT NULL, paciente_nome varchar(255) NOT NULL, paciente_estado varchar(255) NOT NULL, requerimento_id BIGSERIAL NOT NULL, data_criacao timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, status int8 DEFAULT 0 NOT NULL, PRIMARY KEY (requerimento_externo_id));
CREATE TABLE HistoricoRequerimento (historico_id BIGSERIAL NOT NULL, requerimento_id BIGSERIAL NOT NULL, data_modificacao timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, status int8 NOT NULL, descricao varchar(255), user_id_responsavel BIGSERIAL, PRIMARY KEY (historico_id));
CREATE TABLE Consumivel_Requerimento (consumivel_id BIGSERIAL NOT NULL, requerimento_id int8 NOT NULL, quantidade int8 NOT NULL CHECK(quantidade > 0), quantidade_alocada int8 DEFAULT 0 NOT NULL CHECK(quantidade_alocada >= 0), PRIMARY KEY (consumivel_id, requerimento_id));
CREATE TABLE Redistribuicao (redistribuicao_id BIGSERIAL NOT NULL, consumivel_id BIGSERIAL NOT NULL, requerimento_origem BIGSERIAL NOT NULL, requerimento_destino BIGSERIAL NOT NULL, quantidade int8 NOT NULL CHECK(quantidade > 0), data_redistribuicao timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (redistribuicao_id));
CREATE TABLE ValidacaoEntrega (validacao_id BIGSERIAL NOT NULL, requerimento_id BIGSERIAL NOT NULL, user_id_remetente BIGSERIAL NOT NULL, status_validacao int8 NOT NULL, descricao_erro varchar(255), data_validacao timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (validacao_id));
CREATE TABLE PedidoFornecedor (pedido_id BIGSERIAL NOT NULL, consumivel_id BIGSERIAL NOT NULL, fornecedor_id BIGSERIAL NOT NULL, fornecedor_nome varchar(255) NOT NULL, data_pedido timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, data_entrega timestamp, estado int8 DEFAULT 1 NOT NULL CHECK(estado IN (1, 2)), quantidade int8 NOT NULL CHECK(quantidade > 0), PRIMARY KEY (pedido_id));
ALTER TABLE Utilizador ADD CONSTRAINT FKUtilizador385847 FOREIGN KEY (role_id) REFERENCES Role (role_id);
ALTER TABLE Consumivel ADD CONSTRAINT FKConsumivel463977 FOREIGN KEY (tipo_id) REFERENCES Tipo_Consumivel (tipo_id);
ALTER TABLE Setor_Hospital ADD CONSTRAINT FKSetor_Hosp67912 FOREIGN KEY (responsavel_id) REFERENCES Utilizador (utilizador_id);
ALTER TABLE Requerimento ADD CONSTRAINT FKRequerimen984863 FOREIGN KEY (setor_id) REFERENCES Setor_Hospital (setor_id);
ALTER TABLE Requerimento ADD CONSTRAINT FKRequerimen323669 FOREIGN KEY (user_id_pedido) REFERENCES Utilizador (utilizador_id);
ALTER TABLE Requerimento_Externo ADD CONSTRAINT FKRequerimen677167 FOREIGN KEY (requerimento_id) REFERENCES Requerimento (requerimento_id);
ALTER TABLE HistoricoRequerimento ADD CONSTRAINT FKHistoricoR498021 FOREIGN KEY (requerimento_id) REFERENCES Requerimento (requerimento_id);
ALTER TABLE HistoricoRequerimento ADD CONSTRAINT FKHistoricoR892660 FOREIGN KEY (user_id_responsavel) REFERENCES Utilizador (utilizador_id);
ALTER TABLE Consumivel_Requerimento ADD CONSTRAINT FKConsumivel78409 FOREIGN KEY (consumivel_id) REFERENCES Consumivel (consumivel_id);
ALTER TABLE Consumivel_Requerimento ADD CONSTRAINT FKConsumivel771842 FOREIGN KEY (requerimento_id) REFERENCES Requerimento (requerimento_id);
ALTER TABLE Redistribuicao ADD CONSTRAINT FKRedistribu721501 FOREIGN KEY (consumivel_id) REFERENCES Consumivel (consumivel_id);
ALTER TABLE Redistribuicao ADD CONSTRAINT FKRedistribu485399 FOREIGN KEY (requerimento_origem) REFERENCES Requerimento (requerimento_id);
ALTER TABLE Redistribuicao ADD CONSTRAINT FKRedistribu319418 FOREIGN KEY (requerimento_destino) REFERENCES Requerimento (requerimento_id);
ALTER TABLE ValidacaoEntrega ADD CONSTRAINT FKValidacaoE872396 FOREIGN KEY (requerimento_id) REFERENCES Requerimento (requerimento_id);
ALTER TABLE ValidacaoEntrega ADD CONSTRAINT FKValidacaoE239259 FOREIGN KEY (user_id_remetente) REFERENCES Utilizador (utilizador_id);
ALTER TABLE PedidoFornecedor ADD CONSTRAINT FKPedidoForn240759 FOREIGN KEY (consumivel_id) REFERENCES Consumivel (consumivel_id);
ALTER TABLE PedidoFornecedor ADD CONSTRAINT FKPedidoForn168679 FOREIGN KEY (fornecedor_id) REFERENCES Utilizador (utilizador_id);
