#         self.frame_main.setStyleSheet(u"/* LINE EDIT */\n"
# "QLineEdit {\n"
# "	background-color: rgb(27, 29, 35);\n"
# "	border-radius: 5px;\n"
# "	border: 2px solid rgb(27, 29, 35);\n"
# "	padding-left: 10px;\n"
# "}\n"
# "QLineEdit:hover {\n"
# "	border: 2px solid rgb(64, 71, 88);\n"
# "}\n"
# "QLineEdit:focus {\n"
# "	border: 2px solid rgb(91, 101, 124);\n"
# "}\n"
# "\n"
# "/* SCROLL BARS */\n"
# "QScrollBar:horizontal {\n"
# "    border: none;\n"
# "    background: rgb(52, 59, 72);\n"
# "    height: 14px;\n"
# "    margin: 0px 21px 0 21px;\n"
# "	border-radius: 0px;\n"
# "}\n"
# "QScrollBar::handle:horizontal {\n"
# "    background: rgb(85, 170, 255);\n"
# "    min-width: 25px;\n"
# "	border-radius: 7px\n"
# "}\n"
# "QScrollBar::add-line:horizontal {\n"
# "    border: none;\n"
# "    background: rgb(55, 63, 77);\n"
# "    width: 20px;\n"
# "	border-top-right-radius: 7px;\n"
# "    border-bottom-right-radius: 7px;\n"
# "    subcontrol-position: right;\n"
# "    subcontrol-origin: margin;\n"
# "}\n"
# "QScrollBar::sub-line:horizontal {\n"
# "    border: none;\n"
# "    background: rgb(55, 63, 77);\n"
# "    width: 20px;\n"
# ""
#                         "	border-top-left-radius: 7px;\n"
# "    border-bottom-left-radius: 7px;\n"
# "    subcontrol-position: left;\n"
# "    subcontrol-origin: margin;\n"
# "}\n"
# "QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
# "{\n"
# "     background: none;\n"
# "}\n"
# "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
# "{\n"
# "     background: none;\n"
# "}\n"
# " QScrollBar:vertical {\n"
# "	border: none;\n"
# "    background: rgb(52, 59, 72);\n"
# "    width: 14px;\n"
# "    margin: 21px 0 21px 0;\n"
# "	border-radius: 0px;\n"
# " }\n"
# " QScrollBar::handle:vertical {	\n"
# "	background: rgb(85, 170, 255);\n"
# "    min-height: 25px;\n"
# "	border-radius: 7px\n"
# " }\n"
# " QScrollBar::add-line:vertical {\n"
# "     border: none;\n"
# "    background: rgb(55, 63, 77);\n"
# "     height: 20px;\n"
# "	border-bottom-left-radius: 7px;\n"
# "    border-bottom-right-radius: 7px;\n"
# "     subcontrol-position: bottom;\n"
# "     subcontrol-origin: margin;\n"
# " }\n"
# " QScrollBar::sub-line:vertical {\n"
# "	border: none;\n"
# "    background: rgb(55, 63"
#                         ", 77);\n"
# "     height: 20px;\n"
# "	border-top-left-radius: 7px;\n"
# "    border-top-right-radius: 7px;\n"
# "     subcontrol-position: top;\n"
# "     subcontrol-origin: margin;\n"
# " }\n"
# " QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
# "     background: none;\n"
# " }\n"
# "\n"
# " QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
# "     background: none;\n"
# " }\n"
# "\n"
# "/* CHECKBOX */\n"
# "QCheckBox::indicator {\n"
# "    border: 3px solid rgb(52, 59, 72);\n"
# "	width: 15px;\n"
# "	height: 15px;\n"
# "	border-radius: 10px;\n"
# "    background: rgb(44, 49, 60);\n"
# "}\n"
# "QCheckBox::indicator:hover {\n"
# "    border: 3px solid rgb(58, 66, 81);\n"
# "}\n"
# "QCheckBox::indicator:checked {\n"
# "    background: 3px solid rgb(52, 59, 72);\n"
# "	border: 3px solid rgb(52, 59, 72);	\n"
# "	background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
# "}\n"
# "\n"
# "/* RADIO BUTTON */\n"
# "QRadioButton::indicator {\n"
# "    border: 3px solid rgb(52, 59, 72);\n"
# "	width: 15px;\n"
# "	height: 15px;\n"
# "	border-radius"
#                         ": 10px;\n"
# "    background: rgb(44, 49, 60);\n"
# "}\n"
# "QRadioButton::indicator:hover {\n"
# "    border: 3px solid rgb(58, 66, 81);\n"
# "}\n"
# "QRadioButton::indicator:checked {\n"
# "    background: 3px solid rgb(94, 106, 130);\n"
# "	border: 3px solid rgb(52, 59, 72);	\n"
# "}\n"
# "\n"
# "/* COMBOBOX */\n"
# "QComboBox{\n"
# "	background-color: rgb(27, 29, 35);\n"
# "	border-radius: 5px;\n"
# "	border: 2px solid rgb(27, 29, 35);\n"
# "	padding: 5px;\n"
# "	padding-left: 10px;\n"
# "}\n"
# "QComboBox:hover{\n"
# "	border: 2px solid rgb(64, 71, 88);\n"
# "}\n"
# "QComboBox::drop-down {\n"
# "	subcontrol-origin: padding;\n"
# "	subcontrol-position: top right;\n"
# "	width: 25px; \n"
# "	border-left-width: 3px;\n"
# "	border-left-color: rgba(39, 44, 54, 150);\n"
# "	border-left-style: solid;\n"
# "	border-top-right-radius: 3px;\n"
# "	border-bottom-right-radius: 3px;	\n"
# "	background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
# "	background-position: center;\n"
# "	background-repeat: no-reperat;\n"
# " }\n"
# "QComboBox QAbstractItemView {\n"
# "	color: rgb("
#                         "85, 170, 255);	\n"
# "	background-color: rgb(27, 29, 35);\n"
# "	padding: 10px;\n"
# "	selection-background-color: rgb(39, 44, 54);\n"
# "}\n"
# "\n"
# "/* SLIDERS */\n"
# "QSlider::groove:horizontal {\n"
# "    border-radius: 9px;\n"
# "    height: 18px;\n"
# "	margin: 0px;\n"
# "	background-color: rgb(52, 59, 72);\n"
# "}\n"
# "QSlider::groove:horizontal:hover {\n"
# "	background-color: rgb(55, 62, 76);\n"
# "}\n"
# "QSlider::handle:horizontal {\n"
# "    background-color: rgb(85, 170, 255);\n"
# "    border: none;\n"
# "    height: 18px;\n"
# "    width: 18px;\n"
# "    margin: 0px;\n"
# "	border-radius: 9px;\n"
# "}\n"
# "QSlider::handle:horizontal:hover {\n"
# "    background-color: rgb(105, 180, 255);\n"
# "}\n"
# "QSlider::handle:horizontal:pressed {\n"
# "    background-color: rgb(65, 130, 195);\n"
# "}\n"
# "\n"
# "QSlider::groove:vertical {\n"
# "    border-radius: 9px;\n"
# "    width: 18px;\n"
# "    margin: 0px;\n"
# "	background-color: rgb(52, 59, 72);\n"
# "}\n"
# "QSlider::groove:vertical:hover {\n"
# "	background-color: rgb(55, 62, 76);\n"
# "}\n"
# "QSlider::handle:verti"
#                         "cal {\n"
# "    background-color: rgb(85, 170, 255);\n"
# "	border: none;\n"
# "    height: 18px;\n"
# "    width: 18px;\n"
# "    margin: 0px;\n"
# "	border-radius: 9px;\n"
# "}\n"
# "QSlider::handle:vertical:hover {\n"
# "    background-color: rgb(105, 180, 255);\n"
# "}\n"
# "QSlider::handle:vertical:pressed {\n"
# "    background-color: rgb(65, 130, 195);\n"
# "}\n"
# "\n"
#"")