#         palette = QPalette()
#         brush = QBrush(QColor(255, 255, 255, 255))
#         brush.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
#         brush1 = QBrush(QColor(0, 0, 0, 0))
#         brush1.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Active, QPalette.Button, brush1)
#         brush2 = QBrush(QColor(66, 73, 90, 255))
#         brush2.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Active, QPalette.Light, brush2)
#         brush3 = QBrush(QColor(55, 61, 75, 255))
#         brush3.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
#         brush4 = QBrush(QColor(22, 24, 30, 255))
#         brush4.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
#         brush5 = QBrush(QColor(29, 32, 40, 255))
#         brush5.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
#         brush6 = QBrush(QColor(210, 210, 210, 255))
#         brush6.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Active, QPalette.Text, brush6)
#         palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
#         palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
#         palette.setBrush(QPalette.Active, QPalette.Base, brush1)
#         palette.setBrush(QPalette.Active, QPalette.Window, brush1)
#         brush7 = QBrush(QColor(0, 0, 0, 255))
#         brush7.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Active, QPalette.Shadow, brush7)
#         brush8 = QBrush(QColor(85, 170, 255, 255))
#         brush8.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Active, QPalette.Highlight, brush8)
#         palette.setBrush(QPalette.Active, QPalette.Link, brush8)
#         brush9 = QBrush(QColor(255, 0, 127, 255))
#         brush9.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
#         palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
#         brush10 = QBrush(QColor(44, 49, 60, 255))
#         brush10.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush10)
#         palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#         brush11 = QBrush(QColor(210, 210, 210, 128))
#         brush11.setStyle(Qt.NoBrush)
# #if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
#         palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
# #endif
#         palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
#         palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
#         palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
#         palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
#         palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
#         palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
#         palette.setBrush(QPalette.Inactive, QPalette.Text, brush6)
#         palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
#         palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
#         palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
#         palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#         palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
#         palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush8)
#         palette.setBrush(QPalette.Inactive, QPalette.Link, brush8)
#         palette.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
#         palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
#         palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush10)
#         palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#         brush12 = QBrush(QColor(210, 210, 210, 128))
#         brush12.setStyle(Qt.NoBrush)
# #if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
#         palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
# #endif
#         palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
#         palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
#         palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
#         palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
#         palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
#         palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
#         palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
#         palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
#         palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
#         palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
#         palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#         palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
#         brush13 = QBrush(QColor(51, 153, 255, 255))
#         brush13.setStyle(Qt.SolidPattern)
#         palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush13)
#         palette.setBrush(QPalette.Disabled, QPalette.Link, brush8)
#         palette.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
#         palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
#         palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush10)
#         palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#         brush14 = QBrush(QColor(210, 210, 210, 128))
#         brush14.setStyle(Qt.NoBrush)
# #if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
#         palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
# #endif
#         MainWindow.setPalette(palette)


















