INSERT INTO setor_hospital (nome_setor, localizacao) VALUES 
('Enfermaria', 'Piso 2'),
('Gabinete 32', 'A'),
('Bloco Operatório', '45'),
('Farmácia Hospitalar', 'Piso 1'),
('Laboratório de Análises', 'Sala 14'),
('Radiologia', 'Piso Térreo'),
('Oncologia', 'Bloco C, Piso 4'),
('Fisioterapia', 'Piso 1, Sala 10'),
('Pediatria', 'Bloco D, Piso 2'),
('Cardiologia', 'Prédio A, Piso 5'),
('Ginecologia', 'Prédio B, Sala 22'),
('Psiquiatria', 'Bloco E, Piso 1'),
('Neurologia', 'Piso 3, Ala Norte'),
('Endocrinologia', 'Piso 2, Ala Oeste'),
('Hematologia', 'Piso Térreo, Sala 5'),
('Dermatologia', 'Prédio C, Piso 2'),
('Oftalmologia', 'Piso 1, Ala Sul'),
('Ortopedia', 'Bloco F, Piso 3'),
('Odontologia', 'Prédio A, Piso Térreo');
